version: 0.2

phases:
  pre_build:
    commands:
      - echo "Loggin in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 182399691220.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t devpros_app .
      - echo "Tagging the Docker image..."
      - docker tag devpros_app:latest 182399691220.dkr.ecr.us-east-1.amazonaws.com/devpros_app:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 182399691220.dkr.ecr.us-east-1.amazonaws.com/devpros_app:latest
      - echo "Writing Image Definitions file..."
      - printf '[{"name":"Container-app-python", "imageUri":"182399691220.dkr.ecr.us-east-1.amazonaws.com/devpros_app:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"182399691220.dkr.ecr.us-east-1.amazonaws.com/devpros_app:latest"}' > imageDetail.json
      - echo "Contents of imagedefinitions.json:"
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json

secondary-artifacts:
  DefinitionArtifact:
    files:
      - appspec.json
      - taskdef.json
  ImageArtifact: 
    files:
      - imageDetail.json
